// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7Xs3Ej2ep4tqMenNYTrJFHXkFbRBrnps',
    appId: '1:972755403713:web:c758647fe4ef0a4c6f2540',
    messagingSenderId: '972755403713',
    projectId: 'blood-donor-connect-c5dc9',
    authDomain: 'blood-donor-connect-c5dc9.firebaseapp.com',
    storageBucket: 'blood-donor-connect-c5dc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCC5X7z3k_HKSRhXCa3KX_TXHfqtnuyLxQ',
    appId: '1:972755403713:android:8fad8e26c2494c576f2540',
    messagingSenderId: '972755403713',
    projectId: 'blood-donor-connect-c5dc9',
    storageBucket: 'blood-donor-connect-c5dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMK0UO6nzP0TFgvSpXZp1VxK1_m-e9u10',
    appId: '1:972755403713:ios:700ba5abd24f88106f2540',
    messagingSenderId: '972755403713',
    projectId: 'blood-donor-connect-c5dc9',
    storageBucket: 'blood-donor-connect-c5dc9.firebasestorage.app',
    iosBundleId: 'com.techiguru.bloodDonorConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMK0UO6nzP0TFgvSpXZp1VxK1_m-e9u10',
    appId: '1:972755403713:ios:700ba5abd24f88106f2540',
    messagingSenderId: '972755403713',
    projectId: 'blood-donor-connect-c5dc9',
    storageBucket: 'blood-donor-connect-c5dc9.firebasestorage.app',
    iosBundleId: 'com.techiguru.bloodDonorConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA7Xs3Ej2ep4tqMenNYTrJFHXkFbRBrnps',
    appId: '1:972755403713:web:22ec592693fd09d96f2540',
    messagingSenderId: '972755403713',
    projectId: 'blood-donor-connect-c5dc9',
    authDomain: 'blood-donor-connect-c5dc9.firebaseapp.com',
    storageBucket: 'blood-donor-connect-c5dc9.firebasestorage.app',
  );
}
